[routers]
router1 ansible_host=sandbox-iosxe-latest-1.cisco.com ansible_user=admin ansible_password=C1sco12345
router2 ansible_host=sandbox-iosxr-1.cisco.com ansible_user=admin ansible_password=C1sco12345

[routers:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_port=22

---
- name: Show Data
  hosts: routers
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run show version
    ios_command:
      commands: show version
    register: show_version
  
  - name: display show run version
    debug:
      var: show_version

